apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-victoriametrics
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  victoriametrics-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        type: victoriametrics-metrics-datasource
        access: proxy
        url: http://vmsingle-vm-victoria-metrics-k8s-stack:8428
        isDefault: false
        editable: true
        jsonData:
          {}

