apiVersion: v1
kind: ServiceAccount
metadata:
  name: victoria-metrics
  namespace: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics
  namespace: monitoring
  labels:
    app: victoria-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoria-metrics
  template:
    metadata:
      labels:
        app: victoria-metrics
    spec:
      serviceAccountName: victoria-metrics
      containers:
      - name: victoria-metrics
        image: victoriametrics/victoria-metrics:latest
        args:
        - --storageDataPath=/victoria-metrics-data
        - --httpListenAddr=:8428
        - --insert.maxQueueDuration=1m
        - --search.maxQueueDuration=1m
        ports:
        - name: http
          containerPort: 8428
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: data
          mountPath: /victoria-metrics-data
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
  namespace: monitoring
  labels:
    app: victoria-metrics
spec:
  type: NodePort
  ports:
  - port: 8428
    targetPort: 8428
    nodePort: 30081
    protocol: TCP
    name: http
  selector:
    app: victoria-metrics

